# Generated by Django 3.0.3 on 2020-05-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='telefono',
            new_name='tel',
        ),
    ]
